controllers:
    resource: ../../src/Controller/
    type: annotation
#    prefix: /{_locale}
    prefix:
        en: ''
        ru: '/ru'
        ua: '/ua'
    requirements:
        _locale: '%app_locales%'
    defaults:
        _locale: '%locale%'