version: '3'

services:
    php:
        build:
            context: ./frameworks/symfony
        container_name: php
        depends_on:
        - postgres
        env_file:
        - ./frameworks/symfony/.env
        volumes:
        - ./frameworks/symfony:/srv/symfony:rw,cached

    symfony:
        build:
            context: ./frameworks/symfony
            dockerfile: Dockerfile.nginx
        container_name: symfony
        depends_on:
        - php
        ports:
        - "8080:80"
        volumes:
        - ./frameworks/symfony/public:/srv/symfony/public:ro

    postgres:
        image: postgres:9.6-alpine
        container_name: postgres
        environment:
        - POSTGRES_DB=design_patterns
        - POSTGRES_USER=dp_usr
        - POSTGRES_PASSWORD=p2V5ufpbmKy1KJD
        - PGDATA=/var/lib/postgresql/data/db-files/
        volumes:
        - db-data:/var/lib/postgresql/data:rw
        ports:
        - "5432:5432"

    h2-proxy:
        build:
            context: ./h2-proxy
            dockerfile: ./Dockerfile
        container_name: h2-proxy
        depends_on:
        - symfony
        ports:
        - "80:80"
        - "443:443"

volumes:
    db-data: {}
